// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: aserto/directory/importer/v3/importer.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Aserto.Directory.Importer.V3 {

  /// <summary>Holder for reflection information generated from aserto/directory/importer/v3/importer.proto</summary>
  public static partial class ImporterReflection {

    #region Descriptor
    /// <summary>File descriptor for aserto/directory/importer/v3/importer.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ImporterReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cithc2VydG8vZGlyZWN0b3J5L2ltcG9ydGVyL3YzL2ltcG9ydGVyLnByb3Rv",
            "Ehxhc2VydG8uZGlyZWN0b3J5LmltcG9ydGVyLnYzGidhc2VydG8vZGlyZWN0",
            "b3J5L2NvbW1vbi92My9jb21tb24ucHJvdG8i1wEKDUltcG9ydFJlcXVlc3QS",
            "PQoHb3BfY29kZRgBIAEoDjIkLmFzZXJ0by5kaXJlY3RvcnkuaW1wb3J0ZXIu",
            "djMuT3Bjb2RlUgZvcENvZGUSPAoGb2JqZWN0GAUgASgLMiIuYXNlcnRvLmRp",
            "cmVjdG9yeS5jb21tb24udjMuT2JqZWN0SABSBm9iamVjdBJCCghyZWxhdGlv",
            "bhgGIAEoCzIkLmFzZXJ0by5kaXJlY3RvcnkuY29tbW9uLnYzLlJlbGF0aW9u",
            "SABSCHJlbGF0aW9uQgUKA21zZyLiAQoOSW1wb3J0UmVzcG9uc2USQwoGb2Jq",
            "ZWN0GAEgASgLMisuYXNlcnRvLmRpcmVjdG9yeS5pbXBvcnRlci52My5JbXBv",
            "cnRDb3VudGVyUgZvYmplY3QSRwoIcmVsYXRpb24YAiABKAsyKy5hc2VydG8u",
            "ZGlyZWN0b3J5LmltcG9ydGVyLnYzLkltcG9ydENvdW50ZXJSCHJlbGF0aW9u",
            "EkIKBnN0YXR1cxgDIAEoCzIqLmFzZXJ0by5kaXJlY3RvcnkuaW1wb3J0ZXIu",
            "djMuSW1wb3J0U3RhdHVzUgZzdGF0dXMiYwoNSW1wb3J0Q291bnRlchISCgRy",
            "ZWN2GAEgASgEUgRyZWN2EhAKA3NldBgCIAEoBFIDc2V0EhYKBmRlbGV0ZRgD",
            "IAEoBFIGZGVsZXRlEhQKBWVycm9yGAQgASgEUgVlcnJvciK9AQoMSW1wb3J0",
            "U3RhdHVzEhIKBGNvZGUYASABKA1SBGNvZGUSEAoDbXNnGAIgASgJUgNtc2cS",
            "PAoGb2JqZWN0GAUgASgLMiIuYXNlcnRvLmRpcmVjdG9yeS5jb21tb24udjMu",
            "T2JqZWN0SABSBm9iamVjdBJCCghyZWxhdGlvbhgGIAEoCzIkLmFzZXJ0by5k",
            "aXJlY3RvcnkuY29tbW9uLnYzLlJlbGF0aW9uSABSCHJlbGF0aW9uQgUKA3Jl",
            "cSphCgZPcGNvZGUSEgoOT1BDT0RFX1VOS05PV04QABIOCgpPUENPREVfU0VU",
            "EAESEQoNT1BDT0RFX0RFTEVURRACEiAKHE9QQ09ERV9ERUxFVEVfV0lUSF9S",
            "RUxBVElPTlMQAzJ1CghJbXBvcnRlchJpCgZJbXBvcnQSKy5hc2VydG8uZGly",
            "ZWN0b3J5LmltcG9ydGVyLnYzLkltcG9ydFJlcXVlc3QaLC5hc2VydG8uZGly",
            "ZWN0b3J5LmltcG9ydGVyLnYzLkltcG9ydFJlc3BvbnNlIgAoATABQpACCiBj",
            "b20uYXNlcnRvLmRpcmVjdG9yeS5pbXBvcnRlci52M0INSW1wb3J0ZXJQcm90",
            "b1ABWkhnaXRodWIuY29tL2FzZXJ0by1kZXYvZ28tZGlyZWN0b3J5L2FzZXJ0",
            "by9kaXJlY3RvcnkvaW1wb3J0ZXIvdjM7aW1wb3J0ZXKiAgNBREmqAhxBc2Vy",
            "dG8uRGlyZWN0b3J5LkltcG9ydGVyLlYzygIdQXNlcnRvXERpcmVjdG9yeV9c",
            "SW1wb3J0ZXJcVjPiAilBc2VydG9cRGlyZWN0b3J5X1xJbXBvcnRlclxWM1xH",
            "UEJNZXRhZGF0YeoCH0FzZXJ0bzo6RGlyZWN0b3J5OjpJbXBvcnRlcjo6VjNi",
            "BnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Aserto.Directory.Common.V3.CommonReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Aserto.Directory.Importer.V3.Opcode), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Aserto.Directory.Importer.V3.ImportRequest), global::Aserto.Directory.Importer.V3.ImportRequest.Parser, new[]{ "OpCode", "Object", "Relation" }, new[]{ "Msg" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Aserto.Directory.Importer.V3.ImportResponse), global::Aserto.Directory.Importer.V3.ImportResponse.Parser, new[]{ "Object", "Relation", "Status" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Aserto.Directory.Importer.V3.ImportCounter), global::Aserto.Directory.Importer.V3.ImportCounter.Parser, new[]{ "Recv", "Set", "Delete", "Error" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Aserto.Directory.Importer.V3.ImportStatus), global::Aserto.Directory.Importer.V3.ImportStatus.Parser, new[]{ "Code", "Msg", "Object", "Relation" }, new[]{ "Req" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum Opcode {
    [pbr::OriginalName("OPCODE_UNKNOWN")] Unknown = 0,
    [pbr::OriginalName("OPCODE_SET")] Set = 1,
    [pbr::OriginalName("OPCODE_DELETE")] Delete = 2,
    [pbr::OriginalName("OPCODE_DELETE_WITH_RELATIONS")] DeleteWithRelations = 3,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ImportRequest : pb::IMessage<ImportRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ImportRequest> _parser = new pb::MessageParser<ImportRequest>(() => new ImportRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ImportRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Aserto.Directory.Importer.V3.ImporterReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ImportRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ImportRequest(ImportRequest other) : this() {
      opCode_ = other.opCode_;
      switch (other.MsgCase) {
        case MsgOneofCase.Object:
          Object = other.Object.Clone();
          break;
        case MsgOneofCase.Relation:
          Relation = other.Relation.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ImportRequest Clone() {
      return new ImportRequest(this);
    }

    /// <summary>Field number for the "op_code" field.</summary>
    public const int OpCodeFieldNumber = 1;
    private global::Aserto.Directory.Importer.V3.Opcode opCode_ = global::Aserto.Directory.Importer.V3.Opcode.Unknown;
    /// <summary>
    /// operation Opcode enum value
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Aserto.Directory.Importer.V3.Opcode OpCode {
      get { return opCode_; }
      set {
        opCode_ = value;
      }
    }

    /// <summary>Field number for the "object" field.</summary>
    public const int ObjectFieldNumber = 5;
    /// <summary>
    /// object import message
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Aserto.Directory.Common.V3.Object Object {
      get { return msgCase_ == MsgOneofCase.Object ? (global::Aserto.Directory.Common.V3.Object) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.Object;
      }
    }

    /// <summary>Field number for the "relation" field.</summary>
    public const int RelationFieldNumber = 6;
    /// <summary>
    /// relation import message
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Aserto.Directory.Common.V3.Relation Relation {
      get { return msgCase_ == MsgOneofCase.Relation ? (global::Aserto.Directory.Common.V3.Relation) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.Relation;
      }
    }

    private object msg_;
    /// <summary>Enum of possible cases for the "msg" oneof.</summary>
    public enum MsgOneofCase {
      None = 0,
      Object = 5,
      Relation = 6,
    }
    private MsgOneofCase msgCase_ = MsgOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MsgOneofCase MsgCase {
      get { return msgCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearMsg() {
      msgCase_ = MsgOneofCase.None;
      msg_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ImportRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ImportRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (OpCode != other.OpCode) return false;
      if (!object.Equals(Object, other.Object)) return false;
      if (!object.Equals(Relation, other.Relation)) return false;
      if (MsgCase != other.MsgCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (OpCode != global::Aserto.Directory.Importer.V3.Opcode.Unknown) hash ^= OpCode.GetHashCode();
      if (msgCase_ == MsgOneofCase.Object) hash ^= Object.GetHashCode();
      if (msgCase_ == MsgOneofCase.Relation) hash ^= Relation.GetHashCode();
      hash ^= (int) msgCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (OpCode != global::Aserto.Directory.Importer.V3.Opcode.Unknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) OpCode);
      }
      if (msgCase_ == MsgOneofCase.Object) {
        output.WriteRawTag(42);
        output.WriteMessage(Object);
      }
      if (msgCase_ == MsgOneofCase.Relation) {
        output.WriteRawTag(50);
        output.WriteMessage(Relation);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (OpCode != global::Aserto.Directory.Importer.V3.Opcode.Unknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) OpCode);
      }
      if (msgCase_ == MsgOneofCase.Object) {
        output.WriteRawTag(42);
        output.WriteMessage(Object);
      }
      if (msgCase_ == MsgOneofCase.Relation) {
        output.WriteRawTag(50);
        output.WriteMessage(Relation);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (OpCode != global::Aserto.Directory.Importer.V3.Opcode.Unknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) OpCode);
      }
      if (msgCase_ == MsgOneofCase.Object) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Object);
      }
      if (msgCase_ == MsgOneofCase.Relation) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Relation);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ImportRequest other) {
      if (other == null) {
        return;
      }
      if (other.OpCode != global::Aserto.Directory.Importer.V3.Opcode.Unknown) {
        OpCode = other.OpCode;
      }
      switch (other.MsgCase) {
        case MsgOneofCase.Object:
          if (Object == null) {
            Object = new global::Aserto.Directory.Common.V3.Object();
          }
          Object.MergeFrom(other.Object);
          break;
        case MsgOneofCase.Relation:
          if (Relation == null) {
            Relation = new global::Aserto.Directory.Common.V3.Relation();
          }
          Relation.MergeFrom(other.Relation);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            OpCode = (global::Aserto.Directory.Importer.V3.Opcode) input.ReadEnum();
            break;
          }
          case 42: {
            global::Aserto.Directory.Common.V3.Object subBuilder = new global::Aserto.Directory.Common.V3.Object();
            if (msgCase_ == MsgOneofCase.Object) {
              subBuilder.MergeFrom(Object);
            }
            input.ReadMessage(subBuilder);
            Object = subBuilder;
            break;
          }
          case 50: {
            global::Aserto.Directory.Common.V3.Relation subBuilder = new global::Aserto.Directory.Common.V3.Relation();
            if (msgCase_ == MsgOneofCase.Relation) {
              subBuilder.MergeFrom(Relation);
            }
            input.ReadMessage(subBuilder);
            Relation = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            OpCode = (global::Aserto.Directory.Importer.V3.Opcode) input.ReadEnum();
            break;
          }
          case 42: {
            global::Aserto.Directory.Common.V3.Object subBuilder = new global::Aserto.Directory.Common.V3.Object();
            if (msgCase_ == MsgOneofCase.Object) {
              subBuilder.MergeFrom(Object);
            }
            input.ReadMessage(subBuilder);
            Object = subBuilder;
            break;
          }
          case 50: {
            global::Aserto.Directory.Common.V3.Relation subBuilder = new global::Aserto.Directory.Common.V3.Relation();
            if (msgCase_ == MsgOneofCase.Relation) {
              subBuilder.MergeFrom(Relation);
            }
            input.ReadMessage(subBuilder);
            Relation = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ImportResponse : pb::IMessage<ImportResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ImportResponse> _parser = new pb::MessageParser<ImportResponse>(() => new ImportResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ImportResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Aserto.Directory.Importer.V3.ImporterReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ImportResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ImportResponse(ImportResponse other) : this() {
      object_ = other.object_ != null ? other.object_.Clone() : null;
      relation_ = other.relation_ != null ? other.relation_.Clone() : null;
      status_ = other.status_ != null ? other.status_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ImportResponse Clone() {
      return new ImportResponse(this);
    }

    /// <summary>Field number for the "object" field.</summary>
    public const int ObjectFieldNumber = 1;
    private global::Aserto.Directory.Importer.V3.ImportCounter object_;
    /// <summary>
    /// object import counter
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Aserto.Directory.Importer.V3.ImportCounter Object {
      get { return object_; }
      set {
        object_ = value;
      }
    }

    /// <summary>Field number for the "relation" field.</summary>
    public const int RelationFieldNumber = 2;
    private global::Aserto.Directory.Importer.V3.ImportCounter relation_;
    /// <summary>
    /// relation import counter
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Aserto.Directory.Importer.V3.ImportCounter Relation {
      get { return relation_; }
      set {
        relation_ = value;
      }
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 3;
    private global::Aserto.Directory.Importer.V3.ImportStatus status_;
    /// <summary>
    /// import status
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Aserto.Directory.Importer.V3.ImportStatus Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ImportResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ImportResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Object, other.Object)) return false;
      if (!object.Equals(Relation, other.Relation)) return false;
      if (!object.Equals(Status, other.Status)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (object_ != null) hash ^= Object.GetHashCode();
      if (relation_ != null) hash ^= Relation.GetHashCode();
      if (status_ != null) hash ^= Status.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (object_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Object);
      }
      if (relation_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Relation);
      }
      if (status_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Status);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (object_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Object);
      }
      if (relation_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Relation);
      }
      if (status_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Status);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (object_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Object);
      }
      if (relation_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Relation);
      }
      if (status_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Status);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ImportResponse other) {
      if (other == null) {
        return;
      }
      if (other.object_ != null) {
        if (object_ == null) {
          Object = new global::Aserto.Directory.Importer.V3.ImportCounter();
        }
        Object.MergeFrom(other.Object);
      }
      if (other.relation_ != null) {
        if (relation_ == null) {
          Relation = new global::Aserto.Directory.Importer.V3.ImportCounter();
        }
        Relation.MergeFrom(other.Relation);
      }
      if (other.status_ != null) {
        if (status_ == null) {
          Status = new global::Aserto.Directory.Importer.V3.ImportStatus();
        }
        Status.MergeFrom(other.Status);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (object_ == null) {
              Object = new global::Aserto.Directory.Importer.V3.ImportCounter();
            }
            input.ReadMessage(Object);
            break;
          }
          case 18: {
            if (relation_ == null) {
              Relation = new global::Aserto.Directory.Importer.V3.ImportCounter();
            }
            input.ReadMessage(Relation);
            break;
          }
          case 26: {
            if (status_ == null) {
              Status = new global::Aserto.Directory.Importer.V3.ImportStatus();
            }
            input.ReadMessage(Status);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (object_ == null) {
              Object = new global::Aserto.Directory.Importer.V3.ImportCounter();
            }
            input.ReadMessage(Object);
            break;
          }
          case 18: {
            if (relation_ == null) {
              Relation = new global::Aserto.Directory.Importer.V3.ImportCounter();
            }
            input.ReadMessage(Relation);
            break;
          }
          case 26: {
            if (status_ == null) {
              Status = new global::Aserto.Directory.Importer.V3.ImportStatus();
            }
            input.ReadMessage(Status);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ImportCounter : pb::IMessage<ImportCounter>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ImportCounter> _parser = new pb::MessageParser<ImportCounter>(() => new ImportCounter());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ImportCounter> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Aserto.Directory.Importer.V3.ImporterReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ImportCounter() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ImportCounter(ImportCounter other) : this() {
      recv_ = other.recv_;
      set_ = other.set_;
      delete_ = other.delete_;
      error_ = other.error_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ImportCounter Clone() {
      return new ImportCounter(this);
    }

    /// <summary>Field number for the "recv" field.</summary>
    public const int RecvFieldNumber = 1;
    private ulong recv_;
    /// <summary>
    /// number of messages received
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong Recv {
      get { return recv_; }
      set {
        recv_ = value;
      }
    }

    /// <summary>Field number for the "set" field.</summary>
    public const int SetFieldNumber = 2;
    private ulong set_;
    /// <summary>
    /// number of messages with OPCODE_SET
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong Set {
      get { return set_; }
      set {
        set_ = value;
      }
    }

    /// <summary>Field number for the "delete" field.</summary>
    public const int DeleteFieldNumber = 3;
    private ulong delete_;
    /// <summary>
    /// number of messages with OPCODE_DELETE
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong Delete {
      get { return delete_; }
      set {
        delete_ = value;
      }
    }

    /// <summary>Field number for the "error" field.</summary>
    public const int ErrorFieldNumber = 4;
    private ulong error_;
    /// <summary>
    /// number of messages resulting in error
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong Error {
      get { return error_; }
      set {
        error_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ImportCounter);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ImportCounter other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Recv != other.Recv) return false;
      if (Set != other.Set) return false;
      if (Delete != other.Delete) return false;
      if (Error != other.Error) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Recv != 0UL) hash ^= Recv.GetHashCode();
      if (Set != 0UL) hash ^= Set.GetHashCode();
      if (Delete != 0UL) hash ^= Delete.GetHashCode();
      if (Error != 0UL) hash ^= Error.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Recv != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(Recv);
      }
      if (Set != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(Set);
      }
      if (Delete != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(Delete);
      }
      if (Error != 0UL) {
        output.WriteRawTag(32);
        output.WriteUInt64(Error);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Recv != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(Recv);
      }
      if (Set != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(Set);
      }
      if (Delete != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(Delete);
      }
      if (Error != 0UL) {
        output.WriteRawTag(32);
        output.WriteUInt64(Error);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Recv != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Recv);
      }
      if (Set != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Set);
      }
      if (Delete != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Delete);
      }
      if (Error != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Error);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ImportCounter other) {
      if (other == null) {
        return;
      }
      if (other.Recv != 0UL) {
        Recv = other.Recv;
      }
      if (other.Set != 0UL) {
        Set = other.Set;
      }
      if (other.Delete != 0UL) {
        Delete = other.Delete;
      }
      if (other.Error != 0UL) {
        Error = other.Error;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Recv = input.ReadUInt64();
            break;
          }
          case 16: {
            Set = input.ReadUInt64();
            break;
          }
          case 24: {
            Delete = input.ReadUInt64();
            break;
          }
          case 32: {
            Error = input.ReadUInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Recv = input.ReadUInt64();
            break;
          }
          case 16: {
            Set = input.ReadUInt64();
            break;
          }
          case 24: {
            Delete = input.ReadUInt64();
            break;
          }
          case 32: {
            Error = input.ReadUInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ImportStatus : pb::IMessage<ImportStatus>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ImportStatus> _parser = new pb::MessageParser<ImportStatus>(() => new ImportStatus());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ImportStatus> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Aserto.Directory.Importer.V3.ImporterReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ImportStatus() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ImportStatus(ImportStatus other) : this() {
      code_ = other.code_;
      msg_ = other.msg_;
      switch (other.ReqCase) {
        case ReqOneofCase.Object:
          Object = other.Object.Clone();
          break;
        case ReqOneofCase.Relation:
          Relation = other.Relation.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ImportStatus Clone() {
      return new ImportStatus(this);
    }

    /// <summary>Field number for the "code" field.</summary>
    public const int CodeFieldNumber = 1;
    private uint code_;
    /// <summary>
    /// gRPC status code (google.golang.org/grpc/codes)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Code {
      get { return code_; }
      set {
        code_ = value;
      }
    }

    /// <summary>Field number for the "msg" field.</summary>
    public const int MsgFieldNumber = 2;
    private string msg_ = "";
    /// <summary>
    /// gRPC status message (google.golang.org/grpc/status)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Msg {
      get { return msg_; }
      set {
        msg_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "object" field.</summary>
    public const int ObjectFieldNumber = 5;
    /// <summary>
    /// failed object import message
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Aserto.Directory.Common.V3.Object Object {
      get { return reqCase_ == ReqOneofCase.Object ? (global::Aserto.Directory.Common.V3.Object) req_ : null; }
      set {
        req_ = value;
        reqCase_ = value == null ? ReqOneofCase.None : ReqOneofCase.Object;
      }
    }

    /// <summary>Field number for the "relation" field.</summary>
    public const int RelationFieldNumber = 6;
    /// <summary>
    /// failed relation import message
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Aserto.Directory.Common.V3.Relation Relation {
      get { return reqCase_ == ReqOneofCase.Relation ? (global::Aserto.Directory.Common.V3.Relation) req_ : null; }
      set {
        req_ = value;
        reqCase_ = value == null ? ReqOneofCase.None : ReqOneofCase.Relation;
      }
    }

    private object req_;
    /// <summary>Enum of possible cases for the "req" oneof.</summary>
    public enum ReqOneofCase {
      None = 0,
      Object = 5,
      Relation = 6,
    }
    private ReqOneofCase reqCase_ = ReqOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ReqOneofCase ReqCase {
      get { return reqCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearReq() {
      reqCase_ = ReqOneofCase.None;
      req_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ImportStatus);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ImportStatus other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Code != other.Code) return false;
      if (Msg != other.Msg) return false;
      if (!object.Equals(Object, other.Object)) return false;
      if (!object.Equals(Relation, other.Relation)) return false;
      if (ReqCase != other.ReqCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Code != 0) hash ^= Code.GetHashCode();
      if (Msg.Length != 0) hash ^= Msg.GetHashCode();
      if (reqCase_ == ReqOneofCase.Object) hash ^= Object.GetHashCode();
      if (reqCase_ == ReqOneofCase.Relation) hash ^= Relation.GetHashCode();
      hash ^= (int) reqCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Code != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Code);
      }
      if (Msg.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Msg);
      }
      if (reqCase_ == ReqOneofCase.Object) {
        output.WriteRawTag(42);
        output.WriteMessage(Object);
      }
      if (reqCase_ == ReqOneofCase.Relation) {
        output.WriteRawTag(50);
        output.WriteMessage(Relation);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Code != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Code);
      }
      if (Msg.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Msg);
      }
      if (reqCase_ == ReqOneofCase.Object) {
        output.WriteRawTag(42);
        output.WriteMessage(Object);
      }
      if (reqCase_ == ReqOneofCase.Relation) {
        output.WriteRawTag(50);
        output.WriteMessage(Relation);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Code != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Code);
      }
      if (Msg.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Msg);
      }
      if (reqCase_ == ReqOneofCase.Object) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Object);
      }
      if (reqCase_ == ReqOneofCase.Relation) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Relation);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ImportStatus other) {
      if (other == null) {
        return;
      }
      if (other.Code != 0) {
        Code = other.Code;
      }
      if (other.Msg.Length != 0) {
        Msg = other.Msg;
      }
      switch (other.ReqCase) {
        case ReqOneofCase.Object:
          if (Object == null) {
            Object = new global::Aserto.Directory.Common.V3.Object();
          }
          Object.MergeFrom(other.Object);
          break;
        case ReqOneofCase.Relation:
          if (Relation == null) {
            Relation = new global::Aserto.Directory.Common.V3.Relation();
          }
          Relation.MergeFrom(other.Relation);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Code = input.ReadUInt32();
            break;
          }
          case 18: {
            Msg = input.ReadString();
            break;
          }
          case 42: {
            global::Aserto.Directory.Common.V3.Object subBuilder = new global::Aserto.Directory.Common.V3.Object();
            if (reqCase_ == ReqOneofCase.Object) {
              subBuilder.MergeFrom(Object);
            }
            input.ReadMessage(subBuilder);
            Object = subBuilder;
            break;
          }
          case 50: {
            global::Aserto.Directory.Common.V3.Relation subBuilder = new global::Aserto.Directory.Common.V3.Relation();
            if (reqCase_ == ReqOneofCase.Relation) {
              subBuilder.MergeFrom(Relation);
            }
            input.ReadMessage(subBuilder);
            Relation = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Code = input.ReadUInt32();
            break;
          }
          case 18: {
            Msg = input.ReadString();
            break;
          }
          case 42: {
            global::Aserto.Directory.Common.V3.Object subBuilder = new global::Aserto.Directory.Common.V3.Object();
            if (reqCase_ == ReqOneofCase.Object) {
              subBuilder.MergeFrom(Object);
            }
            input.ReadMessage(subBuilder);
            Object = subBuilder;
            break;
          }
          case 50: {
            global::Aserto.Directory.Common.V3.Relation subBuilder = new global::Aserto.Directory.Common.V3.Relation();
            if (reqCase_ == ReqOneofCase.Relation) {
              subBuilder.MergeFrom(Relation);
            }
            input.ReadMessage(subBuilder);
            Relation = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
