// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: aserto/directory/openapi/v3/openapi.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Aserto.Directory.V3 {

  /// <summary>Holder for reflection information generated from aserto/directory/openapi/v3/openapi.proto</summary>
  public static partial class OpenapiReflection {

    #region Descriptor
    /// <summary>File descriptor for aserto/directory/openapi/v3/openapi.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static OpenapiReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cilhc2VydG8vZGlyZWN0b3J5L29wZW5hcGkvdjMvb3BlbmFwaS5wcm90bxIT",
            "YXNlcnRvLmRpcmVjdG9yeS52MxoucHJvdG9jLWdlbi1vcGVuYXBpdjIvb3B0",
            "aW9ucy9hbm5vdGF0aW9ucy5wcm90b0LqBAoXY29tLmFzZXJ0by5kaXJlY3Rv",
            "cnkudjNCDE9wZW5hcGlQcm90b1ABWkBnaXRodWIuY29tL2FzZXJ0by1kZXYv",
            "Z28tZGlyZWN0b3J5L2FzZXJ0by9kaXJlY3RvcnkvdjM7ZGlyZWN0b3J5ogID",
            "QURYqgITQXNlcnRvLkRpcmVjdG9yeS5WM8oCFEFzZXJ0b1xEaXJlY3Rvcnlf",
            "XFYz4gIgQXNlcnRvXERpcmVjdG9yeV9cVjNcR1BCTWV0YWRhdGHqAhVBc2Vy",
            "dG86OkRpcmVjdG9yeTo6VjOSQY0DErwBChFEaXJlY3RvcnkgU2VydmljZSJO",
            "CgxBc2VydG8sIEluYy4SKmh0dHBzOi8vZ2l0aHViLmNvbS9hc2VydG8tZGV2",
            "L3BiLWRpcmVjdG9yeRoSc3VwcG9ydEBhc2VydG8uY29tKlIKEkFwYWNoZSAy",
            "LjAgTGljZW5zZRI8aHR0cHM6Ly9naXRodWIuY29tL2FzZXJ0by1kZXYvcGIt",
            "ZGlyZWN0b3J5L2Jsb2IvbWFpbi9MSUNFTlNFMgMzLjEqAwECBDIQYXBwbGlj",
            "YXRpb24vanNvbjoQYXBwbGljYXRpb24vanNvblpMCiYKD0RpcmVjdG9yeUFQ",
            "SUtleRITCAIaDWF1dGhvcml6YXRpb24gAgoiCghUZW5hbnRJRBIWCAIaEGFz",
            "ZXJ0by10ZW5hbnQtaWQgAmIjChMKD0RpcmVjdG9yeUFQSUtleRIACgwKCFRl",
            "bmFudElEEgByMAoVQXNlcnRvIEFQSSBSZWZlcmVuY2UuEhdodHRwczovL2Rv",
            "Y3MuYXNlcnRvLmNvbWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Grpc.Gateway.ProtocGenOpenapiv2.Options.AnnotationsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
