// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: aserto/directory/schema/v2/tenant.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Aserto.Directory.Schema.V2 {

  /// <summary>Holder for reflection information generated from aserto/directory/schema/v2/tenant.proto</summary>
  public static partial class TenantReflection {

    #region Descriptor
    /// <summary>File descriptor for aserto/directory/schema/v2/tenant.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TenantReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cidhc2VydG8vZGlyZWN0b3J5L3NjaGVtYS92Mi90ZW5hbnQucHJvdG8SGmFz",
            "ZXJ0by5kaXJlY3Rvcnkuc2NoZW1hLnYyGhxnb29nbGUvcHJvdG9idWYvc3Ry",
            "dWN0LnByb3RvIsoBChBUZW5hbnRQcm9wZXJ0aWVzEjQKBGtpbmQYASABKA4y",
            "Ji5hc2VydG8uZGlyZWN0b3J5LnNjaGVtYS52Mi5UZW5hbnRLaW5kEhQKDGRp",
            "cmVjdG9yeV92MhgCIAEoCBIZChFkaXJlY3RvcnlfdjJfb25seRgDIAEoCBJD",
            "CgdhY2NvdW50GAQgASgLMi0uYXNlcnRvLmRpcmVjdG9yeS5zY2hlbWEudjIu",
            "QWNjb3VudFByb3BlcnRpZXNIAIgBAUIKCghfYWNjb3VudCJ/ChFBY2NvdW50",
            "UHJvcGVydGllcxIQCghtYXhfb3JncxgBIAEoBRJECg9nZXR0aW5nX3N0YXJ0",
            "ZWQYAyABKAsyJi5hc2VydG8uZGlyZWN0b3J5LnNjaGVtYS52Mi5HdWlkZVN0",
            "YXRlSACIAQFCEgoQX2dldHRpbmdfc3RhcnRlZCJCCgpHdWlkZVN0YXRlEgwK",
            "BHNob3cYASABKAgSJgoFc3RlcHMYAiABKAsyFy5nb29nbGUucHJvdG9idWYu",
            "U3RydWN0KlwKClRlbmFudEtpbmQSFwoTVEVOQU5UX0tJTkRfVU5LTk9XThAA",
            "EhwKGFRFTkFOVF9LSU5EX09SR0FOSVpBVElPThABEhcKE1RFTkFOVF9LSU5E",
            "X0FDQ09VTlQQAkJGWkRnaXRodWIuY29tL2FzZXJ0by1kZXYvZ28tZGlyZWN0",
            "b3J5L2FzZXJ0by9kaXJlY3Rvcnkvc2NoZW1hL3YyO3NjaGVtYWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.StructReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Aserto.Directory.Schema.V2.TenantKind), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Aserto.Directory.Schema.V2.TenantProperties), global::Aserto.Directory.Schema.V2.TenantProperties.Parser, new[]{ "Kind", "DirectoryV2", "DirectoryV2Only", "Account" }, new[]{ "Account" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Aserto.Directory.Schema.V2.AccountProperties), global::Aserto.Directory.Schema.V2.AccountProperties.Parser, new[]{ "MaxOrgs", "GettingStarted" }, new[]{ "GettingStarted" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Aserto.Directory.Schema.V2.GuideState), global::Aserto.Directory.Schema.V2.GuideState.Parser, new[]{ "Show", "Steps" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum TenantKind {
    [pbr::OriginalName("TENANT_KIND_UNKNOWN")] Unknown = 0,
    [pbr::OriginalName("TENANT_KIND_ORGANIZATION")] Organization = 1,
    /// <summary>
    /// personal tenant
    /// </summary>
    [pbr::OriginalName("TENANT_KIND_ACCOUNT")] Account = 2,
  }

  #endregion

  #region Messages
  /// <summary>
  /// Properties of a tenant object
  /// </summary>
  public sealed partial class TenantProperties : pb::IMessage<TenantProperties>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TenantProperties> _parser = new pb::MessageParser<TenantProperties>(() => new TenantProperties());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<TenantProperties> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Aserto.Directory.Schema.V2.TenantReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TenantProperties() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TenantProperties(TenantProperties other) : this() {
      kind_ = other.kind_;
      directoryV2_ = other.directoryV2_;
      directoryV2Only_ = other.directoryV2Only_;
      account_ = other.account_ != null ? other.account_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TenantProperties Clone() {
      return new TenantProperties(this);
    }

    /// <summary>Field number for the "kind" field.</summary>
    public const int KindFieldNumber = 1;
    private global::Aserto.Directory.Schema.V2.TenantKind kind_ = global::Aserto.Directory.Schema.V2.TenantKind.Unknown;
    /// <summary>
    /// The kind of tenant.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Aserto.Directory.Schema.V2.TenantKind Kind {
      get { return kind_; }
      set {
        kind_ = value;
      }
    }

    /// <summary>Field number for the "directory_v2" field.</summary>
    public const int DirectoryV2FieldNumber = 2;
    private bool directoryV2_;
    /// <summary>
    /// Whether or not the v2 directory experience enabled for this tenant.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool DirectoryV2 {
      get { return directoryV2_; }
      set {
        directoryV2_ = value;
      }
    }

    /// <summary>Field number for the "directory_v2_only" field.</summary>
    public const int DirectoryV2OnlyFieldNumber = 3;
    private bool directoryV2Only_;
    /// <summary>
    /// If true, the tenant cannot be reverted to the v1 directory experience.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool DirectoryV2Only {
      get { return directoryV2Only_; }
      set {
        directoryV2Only_ = value;
      }
    }

    /// <summary>Field number for the "account" field.</summary>
    public const int AccountFieldNumber = 4;
    private global::Aserto.Directory.Schema.V2.AccountProperties account_;
    /// <summary>
    /// Additional properties that are only set accounts (personal tennats).
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Aserto.Directory.Schema.V2.AccountProperties Account {
      get { return account_; }
      set {
        account_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as TenantProperties);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(TenantProperties other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Kind != other.Kind) return false;
      if (DirectoryV2 != other.DirectoryV2) return false;
      if (DirectoryV2Only != other.DirectoryV2Only) return false;
      if (!object.Equals(Account, other.Account)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Kind != global::Aserto.Directory.Schema.V2.TenantKind.Unknown) hash ^= Kind.GetHashCode();
      if (DirectoryV2 != false) hash ^= DirectoryV2.GetHashCode();
      if (DirectoryV2Only != false) hash ^= DirectoryV2Only.GetHashCode();
      if (account_ != null) hash ^= Account.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Kind != global::Aserto.Directory.Schema.V2.TenantKind.Unknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Kind);
      }
      if (DirectoryV2 != false) {
        output.WriteRawTag(16);
        output.WriteBool(DirectoryV2);
      }
      if (DirectoryV2Only != false) {
        output.WriteRawTag(24);
        output.WriteBool(DirectoryV2Only);
      }
      if (account_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Account);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Kind != global::Aserto.Directory.Schema.V2.TenantKind.Unknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Kind);
      }
      if (DirectoryV2 != false) {
        output.WriteRawTag(16);
        output.WriteBool(DirectoryV2);
      }
      if (DirectoryV2Only != false) {
        output.WriteRawTag(24);
        output.WriteBool(DirectoryV2Only);
      }
      if (account_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Account);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Kind != global::Aserto.Directory.Schema.V2.TenantKind.Unknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Kind);
      }
      if (DirectoryV2 != false) {
        size += 1 + 1;
      }
      if (DirectoryV2Only != false) {
        size += 1 + 1;
      }
      if (account_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Account);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(TenantProperties other) {
      if (other == null) {
        return;
      }
      if (other.Kind != global::Aserto.Directory.Schema.V2.TenantKind.Unknown) {
        Kind = other.Kind;
      }
      if (other.DirectoryV2 != false) {
        DirectoryV2 = other.DirectoryV2;
      }
      if (other.DirectoryV2Only != false) {
        DirectoryV2Only = other.DirectoryV2Only;
      }
      if (other.account_ != null) {
        if (account_ == null) {
          Account = new global::Aserto.Directory.Schema.V2.AccountProperties();
        }
        Account.MergeFrom(other.Account);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Kind = (global::Aserto.Directory.Schema.V2.TenantKind) input.ReadEnum();
            break;
          }
          case 16: {
            DirectoryV2 = input.ReadBool();
            break;
          }
          case 24: {
            DirectoryV2Only = input.ReadBool();
            break;
          }
          case 34: {
            if (account_ == null) {
              Account = new global::Aserto.Directory.Schema.V2.AccountProperties();
            }
            input.ReadMessage(Account);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Kind = (global::Aserto.Directory.Schema.V2.TenantKind) input.ReadEnum();
            break;
          }
          case 16: {
            DirectoryV2 = input.ReadBool();
            break;
          }
          case 24: {
            DirectoryV2Only = input.ReadBool();
            break;
          }
          case 34: {
            if (account_ == null) {
              Account = new global::Aserto.Directory.Schema.V2.AccountProperties();
            }
            input.ReadMessage(Account);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class AccountProperties : pb::IMessage<AccountProperties>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AccountProperties> _parser = new pb::MessageParser<AccountProperties>(() => new AccountProperties());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<AccountProperties> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Aserto.Directory.Schema.V2.TenantReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AccountProperties() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AccountProperties(AccountProperties other) : this() {
      maxOrgs_ = other.maxOrgs_;
      gettingStarted_ = other.gettingStarted_ != null ? other.gettingStarted_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AccountProperties Clone() {
      return new AccountProperties(this);
    }

    /// <summary>Field number for the "max_orgs" field.</summary>
    public const int MaxOrgsFieldNumber = 1;
    private int maxOrgs_;
    /// <summary>
    /// Maximum number of organizations that can be created in this account.
    /// If -1, there is no limit.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int MaxOrgs {
      get { return maxOrgs_; }
      set {
        maxOrgs_ = value;
      }
    }

    /// <summary>Field number for the "getting_started" field.</summary>
    public const int GettingStartedFieldNumber = 3;
    private global::Aserto.Directory.Schema.V2.GuideState gettingStarted_;
    /// <summary>
    /// Tracks the account owner's progress through the getting-started guide.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Aserto.Directory.Schema.V2.GuideState GettingStarted {
      get { return gettingStarted_; }
      set {
        gettingStarted_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as AccountProperties);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(AccountProperties other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MaxOrgs != other.MaxOrgs) return false;
      if (!object.Equals(GettingStarted, other.GettingStarted)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (MaxOrgs != 0) hash ^= MaxOrgs.GetHashCode();
      if (gettingStarted_ != null) hash ^= GettingStarted.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (MaxOrgs != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(MaxOrgs);
      }
      if (gettingStarted_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(GettingStarted);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (MaxOrgs != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(MaxOrgs);
      }
      if (gettingStarted_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(GettingStarted);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (MaxOrgs != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MaxOrgs);
      }
      if (gettingStarted_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(GettingStarted);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(AccountProperties other) {
      if (other == null) {
        return;
      }
      if (other.MaxOrgs != 0) {
        MaxOrgs = other.MaxOrgs;
      }
      if (other.gettingStarted_ != null) {
        if (gettingStarted_ == null) {
          GettingStarted = new global::Aserto.Directory.Schema.V2.GuideState();
        }
        GettingStarted.MergeFrom(other.GettingStarted);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            MaxOrgs = input.ReadInt32();
            break;
          }
          case 26: {
            if (gettingStarted_ == null) {
              GettingStarted = new global::Aserto.Directory.Schema.V2.GuideState();
            }
            input.ReadMessage(GettingStarted);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            MaxOrgs = input.ReadInt32();
            break;
          }
          case 26: {
            if (gettingStarted_ == null) {
              GettingStarted = new global::Aserto.Directory.Schema.V2.GuideState();
            }
            input.ReadMessage(GettingStarted);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// The state of a user's progress through the console's getting started guide.
  /// </summary>
  public sealed partial class GuideState : pb::IMessage<GuideState>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GuideState> _parser = new pb::MessageParser<GuideState>(() => new GuideState());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GuideState> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Aserto.Directory.Schema.V2.TenantReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GuideState() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GuideState(GuideState other) : this() {
      show_ = other.show_;
      steps_ = other.steps_ != null ? other.steps_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GuideState Clone() {
      return new GuideState(this);
    }

    /// <summary>Field number for the "show" field.</summary>
    public const int ShowFieldNumber = 1;
    private bool show_;
    /// <summary>
    /// Whether or not to display the getting started guide.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Show {
      get { return show_; }
      set {
        show_ = value;
      }
    }

    /// <summary>Field number for the "steps" field.</summary>
    public const int StepsFieldNumber = 2;
    private global::Google.Protobuf.WellKnownTypes.Struct steps_;
    /// <summary>
    /// Progress information about individual steps in the guide.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Struct Steps {
      get { return steps_; }
      set {
        steps_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GuideState);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GuideState other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Show != other.Show) return false;
      if (!object.Equals(Steps, other.Steps)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Show != false) hash ^= Show.GetHashCode();
      if (steps_ != null) hash ^= Steps.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Show != false) {
        output.WriteRawTag(8);
        output.WriteBool(Show);
      }
      if (steps_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Steps);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Show != false) {
        output.WriteRawTag(8);
        output.WriteBool(Show);
      }
      if (steps_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Steps);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Show != false) {
        size += 1 + 1;
      }
      if (steps_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Steps);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GuideState other) {
      if (other == null) {
        return;
      }
      if (other.Show != false) {
        Show = other.Show;
      }
      if (other.steps_ != null) {
        if (steps_ == null) {
          Steps = new global::Google.Protobuf.WellKnownTypes.Struct();
        }
        Steps.MergeFrom(other.Steps);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Show = input.ReadBool();
            break;
          }
          case 18: {
            if (steps_ == null) {
              Steps = new global::Google.Protobuf.WellKnownTypes.Struct();
            }
            input.ReadMessage(Steps);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Show = input.ReadBool();
            break;
          }
          case 18: {
            if (steps_ == null) {
              Steps = new global::Google.Protobuf.WellKnownTypes.Struct();
            }
            input.ReadMessage(Steps);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
